# Config file for automatic testing at travis-ci.org

language: python

python:
  #- "2.6"
  - "2.7"
  - "3.2"

install:
   # deactivate the virtualenv so that numpy can be quickly installed
   - deactivate 
   - sudo apt-get install -qq python-numpy python-sphinx

script:
  - cd tests
  - nosetests

  - cd ../doc
  - make html
