# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7

env:
    - version=without_numpy
    - version=with_numpy

before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

install:
    - if [[ $version == without_numpy && $TRAVIS_PYTHON_VERSION != 3.7 ]]; then conda create -q -n test_env python=$TRAVIS_PYTHON_VERSION pytest coverage; fi
    - if [[ $version == with_numpy    && $TRAVIS_PYTHON_VERSION != 3.7 ]]; then conda create -q -n test_env python=$TRAVIS_PYTHON_VERSION numpy pytest coverage; fi
    - if [[ $version == without_numpy && $TRAVIS_PYTHON_VERSION == 3.7 ]]; then conda create -q -n test_env python=3.7 pytest coverage; fi
    - if [[ $version == with_numpy    && $TRAVIS_PYTHON_VERSION == 3.7 ]]; then conda create -q -n test_env python=3.7 numpy pytest coverage; fi
    - source activate test_env
    - python setup.py install
    - pip install codecov

script:
    - cd tests
    - pytest
    - coverage run --source=asteval test_asteval.py
    - coverage report -m

after_success:
    - codecov
