# Config file for automatic testing at travis-ci.org
language: python

python:
    - 2.6

matrix:
    include:
        - python: 2.6
          env:
            - PYTHON=python
            - PYVER=2.x
        - python: 2.7
          env:
            - PYTHON=python
            - PYVER=2.x
        - python: 3.2
          env:
            - PYTHON=python3
            - PYVER=3.x
        - python: 3.3
          env:
            - PYTHON=python3
            - PYVER=3.x


virtualenv:
    system_site_packages: true

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

    - sudo apt-get update
    - sudo apt-get install $PYTHON-setuptools
    - sudo apt-get install $PYTHON-numpy
    - sudo apt-get install $PYTHON-sphinx
    - sudo apt-get install $PYTHON-nose

install:
    - sudo $PYTHON setup.py install

script:
    # Execute the unit tests
    - cd tests
    - nosetests
    # Generate the docs
    - if [[ $PYVER == '2.x' ]]; then
    -   cd ../doc
    -   make html
    - fi
