# Config file for automatic testing at travis-ci.org
language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

install:
    - pip install .
    - pip install -r requirements.txt

script:
    - cd tests
    - nosetests
    # Generate the docs
    - if [[ $PYVER == '2.x' ]]; then
    -   cd ../doc
    -   make html
    - fi
