# Config file for automatic testing at travis-ci.org
language: python


matrix:
    include:
        - python: 2.6
          env:
            - PYTHON=python2.6
            - BUILDDOC=0
        - python: 2.7
          env:
            - PYTHON=python
            - BUILDDOC=1
        - python: 3.2
          env:
            - PYTHON=python3
            - BUILDDOC=0
        - python: 3.3
          env:
            - PYTHON=python3.3
            - BUILDDOC=0

virtualenv:
    system_site_packages: true

before_install:

install:
    - sudo pip install -r requirements.txt
    - sudo pip install .
    - if [[ $BUILDDOC == '1' ]]; then
    -    sudo pip install sphinx
    - fi

script:
    - cd tests
    - nosetests
    # build docs
    - if [[ $BUILDDOC == '1' ]]; then
    -   cd ../doc
    -   make html
    - fi
