# Config file for automatic testing at travis-ci.org
language: python


matrix:
    include:
        - python: 2.6
          env:
            - PYTHON=python
            - BUILDDOC=0
        - python: 2.7
          env:
            - PYTHON=python
            - BUILDDOC=0
        - python: 3.2
          env:
            - PYTHON=python3
            - BUILDDOC=0
        - python: 3.3
          env:
            - PYTHON=python3
            - BUILDDOC=0

virtualenv:
    system_site_packages: true

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sudo apt-get update
    - sudo apt-get install $PYTHON-nose
    - sudo apt-get install $PYTHON-numpy
    - if [[ $BUILDDOC == '1' ]]; then
    -    sudo apt-get install $PYTHON-sphinx
    - fi

install:
    - sudo $PYTHON setup.py install

script:
    - cd tests
    - nosetests
    # build docs
    - if [[ $BUILDDOC == '1' ]]; then
    -   cd ../doc
    -   make html
    - fi
