# Config file for automatic testing at travis-ci.org
language: python


matrix:
    include:
        - python: 2.7
          env:
            - PYTHON=python
            - BUILDDOC=1
        - python: 3.2
          env:
            - PYTHON=python3
            - BUILDDOC=0

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get update
    - sudo apt-get install $PYTHON-setuptools
    - sudo apt-get install $PYTHON-numpy
    - sudo apt-get install $PYTHON-nose
    - if [[ $BUILDDOC == '1' ]]; then
    -    sudo apt-get install $PYTHON-sphinx
    - fi

install:
    - sudo $PYTHON setup.py install
    - sudo pip install .

script:
    - cd tests
    - nosetests
    # build docs
    - if [[ $BUILDDOC == '1' ]]; then
    -   cd ../doc
    -   make html
    - fi
