# Config file for automatic testing at travis-ci.org
language: python


matrix:
    include:
        - python: 2.6
          env:
            - PYTHON=python
            - PYVER=3.x
        - python: 2.7
          env:
            - PYTHON=python
            - PYVER=2.x
        - python: 3.2
          env:
            - PYTHON=python3
            - PYVER=3.x
        - python: 3.3
          env:
            - PYTHON=python3
            - PYVER=3.x


before_install:
    - sudo apt-get update
    - sudo apt-get install $PYTHON-numpy
    - sudo apt-get install $PYTHON-nose
    - if [[ $PYVER == '2.x' ]]; then
    -    sudo apt-get install $PYTHON-sphinx
    - fi

install:
    - sudo $PYTHON setup.py install

script:
    - cd tests
    - nosetests
    # build docs
    - if [[ $PYVER == '2.x' ]]; then
    -   cd ../doc
    -   make html
    - fi
